version: 0.2

env:
  parameter-store:
    AWS_DEFAULT_REGION: "/Prod/DokugakuEngineer/Api/AWS_DEFAULT_REGION"
    AWS_NGINX_REPOSITORY_URI: "/Prod/DokugakuEngineer/Api/AWS_NGINX_REPOSITORY_URI"
    AWS_API_REPOSITORY_URI: "/Prod/DokugakuEngineer/Api/AWS_API_REPOSITORY_URI"
    DOCKERHUB_USERNAME: "/Prod/DokugakuEngineer/Api/DOCKERHUB_USERNAME"
    DOCKERHUB_PASSWORD: "/Prod/DokugakuEngineer/Api/DOCKERHUB_PASSWORD"

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo Logging in to Docker...
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  build:
    commands:
      - echo API Build started on `date`
      - echo Building the Docker image...
      - docker build -t $AWS_NGINX_REPOSITORY_URI:latest -f docker/nginx/Dockerfile . --build-arg env=production
      - docker build -t $AWS_API_REPOSITORY_URI:latest -f docker/api/Dockerfile . --build-arg env=production --build-arg ssm_agent_code=$SSM_AGENT_CODE --build-arg ssm_agent_id=$SSM_AGENT_ID
      - docker tag $AWS_NGINX_REPOSITORY_URI:latest $AWS_NGINX_REPOSITORY_URI:$IMAGE_TAG
      - docker tag $AWS_API_REPOSITORY_URI:latest $AWS_API_REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $AWS_NGINX_REPOSITORY_URI:latest
      - docker push $AWS_NGINX_REPOSITORY_URI:$IMAGE_TAG
      - docker push $AWS_API_REPOSITORY_URI:latest
      - docker push $AWS_API_REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"nginx","imageUri":"%s"},{"name":"api","imageUri":"%s"}]' $AWS_NGINX_REPOSITORY_URI:$IMAGE_TAG $AWS_API_REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
